## NumPy
Usually you'll encounter "NumPy arrays", which are multi-dimensional array objects. It is easy to create a Pandas DataFrame from a NumPy array, and Pandas DataFrames can be cast as NumPy arrays. 


One of the most common, of the many, ways to create a NumPy array is to create one from a list by passing it to the np.array() function.


In [23]:
list1 = [1,2,3,4,3.4,'S',True]
list2= [2,3,4]
list2 = [i+2 for i in list2]
list2

[4, 5, 6]

In [30]:
import numpy as np
list2 = [3,4,5,6]
print (type(list2))
arr2 = np.array(list2,dtype= float)
type (arr2)
arr2

<class 'list'>


array([3., 4., 5., 6.])

In [29]:
arr2 *= 2
arr2

array([ 6,  8, 10, 12])

In [10]:
print (arr3)
arr3 = arr3+2
arr3

[4 5 8 9]


array([ 6,  7, 10, 11])

In [11]:
arr3 = np.array(list3, dtype = float)
arr3

array([2., 3., 6., 7.])

In [9]:
type (arr2)

numpy.ndarray

In [31]:
arr3_s = arr2.astype('int').astype('str')
arr3_s

array(['3', '4', '5', '6'], dtype='<U11')

In [14]:
arr_obj = np.array([1,'a'],dtype= 'object')
print  (arr_obj )
type(arr_obj)

[1 'a']


numpy.ndarray

In [15]:
arr_list = arr_obj.tolist()
type(arr_list)

list

In [32]:
list3 = [[1,2,3],[4,5,6],[7,8,9],[3,5,8]]
arr3 = np.array(list3)
print (arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [3 5 8]]


In [33]:
arr3.shape

(4, 3)

In [19]:
arr3.size

12

In [21]:
arr3.dtype
type(arr3)

numpy.ndarray

In [1]:
import numpy as np
list22= [5,6,6,11,-3,-3,-1,2,3,8]
list_arr= np.array(list22)
M = list_arr.mean()
M

3.4

In [2]:
SD = list_arr.std()
SD

4.454211490264018

### The Basics

In [5]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [6]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])  # a list within a list
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [8]:
# Get Shape
b.shape

(2, 3)

In [9]:
# Get Type
a.dtype

dtype('int32')

In [13]:
# Get number of elements
a.size

3

### Accessing/Changing specific elements, rows, columns, etc

In [45]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [14]:
# Get a specific element [r, c]
a[1, 5]

13

In [15]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [73]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[-2, -4, -4],
       [ 6,  6,  3],
       [ 3,  2,  2]])

In [76]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Mathematics

In [111]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [109]:
a + 2

array([5, 6, 7, 8])

In [102]:
a - 2

array([-1,  0,  1,  2])

In [103]:
a * 2

array([2, 4, 6, 8])

In [104]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [118]:
b = np.array([1,0,1,0])
a + b

array([1, 0, 3, 0])

In [113]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)